#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pox
Version  : 0.3.0
Release  : 1
URL      : https://github.com/uqfoundation/pox/releases/download/pox-0.3.0/pox-0.3.0.tar.gz
Source0  : https://github.com/uqfoundation/pox/releases/download/pox-0.3.0/pox-0.3.0.tar.gz
Summary  : utilities for filesystem exploration and automated builds
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pox-bin = %{version}-%{release}
Requires: pox-license = %{version}-%{release}
Requires: pox-python = %{version}-%{release}
Requires: pox-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
--------------------------------------------------------------
pox: utilities for filesystem exploration and automated builds
--------------------------------------------------------------

%package bin
Summary: bin components for the pox package.
Group: Binaries
Requires: pox-license = %{version}-%{release}

%description bin
bin components for the pox package.


%package license
Summary: license components for the pox package.
Group: Default

%description license
license components for the pox package.


%package python
Summary: python components for the pox package.
Group: Default
Requires: pox-python3 = %{version}-%{release}

%description python
python components for the pox package.


%package python3
Summary: python3 components for the pox package.
Group: Default
Requires: python3-core
Provides: pypi(pox)

%description python3
python3 components for the pox package.


%prep
%setup -q -n pox-0.3.0
cd %{_builddir}/pox-0.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1638309342
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pox
cp %{_builddir}/pox-0.3.0/LICENSE %{buildroot}/usr/share/package-licenses/pox/5a4d5da357f0df5d1be0dd74d0e4cc9830053a7c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pox

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pox/5a4d5da357f0df5d1be0dd74d0e4cc9830053a7c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
